// This is a generated file 
// Generated by ResouceKit 
// You can write custom imoprt XXXX logic
import UIKit
protocol XibProtocol {
	var name: String { get } 
	 func nib() -> UINib
}
extension UITableView { 
	internal func register(_ nib: XibProtocol) -> Void {
		register(nib.nib(), forCellReuseIdentifier: nib.name)
	}
	internal func register(nibs: [XibProtocol]) -> Void {
		nibs.forEach(register)
	}
	 
} 

extension UICollectionView { 
	internal func register(_ nib: XibProtocol) -> Void {
		register(nib.nib(), forCellWithReuseIdentifier: nib.name)
	}
	internal func register(nibs: [XibProtocol]) -> Void {
		nibs.forEach(register)
	}
	 
} 

extension UIImage { 
	
	struct Asset {
	
	
	}
	struct Resource {
	
	
	} 
} 

extension String { 
	
	struct Localized {
	
	
	} 
} 

